# kind: Service
# apiVersion: v1
# metadata:
#   name: train-schedule-service
# spec:
#   type: NodePort
#   selector:
#     app: train-schedule
#   ports:
#   - protocol: TCP
#     port: 8080
#     nodePort: 30080


apiVersion: v1
kind: Service
metadata:
  labels:
    app: train-schedule
    k8s-app: train-schedule
  name: train-schedule-loadbalancer
  namespace: staging
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: train-schedule
